version: '3'
services:
  ss-local-clusters:
    image: kaive/shadowsocks-libev
    user: root
    volumes:
      - ./shadowsocks/ss-run.sh:/entrypoint.sh
      - ./shadowsocks/ss-cli.lst:/ss.lst
    command: /entrypoint.sh
    networks:
      - proxies
    # ports:
    #   - "9000-9131:9000-9131"

  # load balansce
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - ss-local-clusters
    networks:
      - proxies
    ports:
      - ${HAPROXY_PORT}:8000

  privoxy:
    image: vimagick/privoxy
    ports:
      - ${PRIVOXY_PORT}:8119
    volumes:
      - ./privoxy/privoxy.cfg:/etc/privoxy/config
      - ./privoxy/default.action:/etc/privoxy/default.action
      - ./privoxy/user.action:/etc/privoxy/user.action
    networks:
      - proxies

networks:
  proxies:
    driver: bridge
