version: '3'
services:
  ss-local-clusters:
    image: shadowsocks/shadowsocks-libev
    user: root
    volumes:
      - ./ss-run.sh:/entrypoint.sh
      - ./ss.lst:/ss.lst
    command: /entrypoint.sh
    networks:
      - proxies

  # load balansce
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - proxies
    ports:
      - ${HAPROXY_PORT}:8001

  privoxy:
    image: vimagick/privoxy
    ports:
      - ${PRIVOXY_PORT}:8119
    volumes:
      - ./privoxy.cfg:/etc/privoxy/config
    networks:
      - proxies

networks:
  proxies:
    driver: bridge
